{
 "title": "App",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Requests & Handles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=\"$job\"}"
    },
    {
     "expr": "nodejs_active_requests_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{job=\"$job\"}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=\"$job\"}"
    },
    {
     "expr": "nodejs_heap_space_size_total_bytes{job=\"$job\"}"
    },
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Request Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_requests_total{job=\"$job\"}[30s])"
    }
   ]
  },
  {
   "title": "Request Timings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds{job=\"$job\", quantile='0.5'}",
     "legendFormat": "Request duration (50% quantile)"
    },
    {
     "expr": "http_request_duration_seconds{job=\"$job\", quantile='0.95'}",
     "legendFormat": "Request duration (95% quantile)"
    },
    {
     "expr": "http_request_duration_seconds{job=\"$job\", quantile='0.99'}",
     "legendFormat": "Request duration (99% quantile)"
    },
    {
     "expr": "http_request_duration_seconds_sum / http_request_duration_seconds_count",
     "legendFormat": "Average request duration"
    }
   ]
  }
 ]
}